ref_list = [
'[1] S. Farah et al. / Advanced Drug Delivery Reviews 107 (2016) 367–392',
'[2] Polymer Bulletin, 2019, 76, 1061–1079',
'[3]Singh, R., Bathaei, M. J., Istif, E., & Beker, L. (2020). A review of bioresorbable implantable medical devices: materials, fabrication, and implementation. Advanced Healthcare Materials, 9(18), 2000790.',
'[4]Källrot, M., Edlund, U., & Albertsson, A. C. (2007). Covalent grafting of poly (L-lactide) to tune the in vitro degradation rate. Biomacromolecules, 8(8), 2492-2496.',
'[5]McAdam, B., Brennan Fournet, M., McDonald, P., & Mojicevic, M. (2020). Production of polyhydroxybutyrate (PHB) and factors impacting its chemical and mechanical characteristics. Polymers, 12(12), 2908.',
'[6]Weir, N. A., Buchanan, F. J., Orr, J. F., & Dickson, G. R. (2004). Degradation of poly-L-lactide. Part 1: in vitro and in vivo physiological temperature degradation. Proceedings of the Institution of Mechanical Engineers, Part H: Journal of Engineering in Medicine, 218(5), 307-319.',
'[7] RSC Adv., 2017,7, 41593-41602',
'[8]Low, Y. J., Andriyana, A., Ang, B. C., & Zainal Abidin, N. I. (2020). Bioresorbable and degradable behaviors of PGA: Current state and future prospects. Polymer Engineering & Science, 60(11), 2657-2675.',
'[9]You, Y., Lee, S. W., Youk, J. H., Min, B. M., Lee, S. J., & Park, W. H. (2005). In vitro degradation behaviour of non-porous ultra-fine poly (glycolic acid)/poly (l-lactic acid) fibres and porous ultra-fine poly (glycolic acid) fibres. Polymer Degradation and Stability, 90(3), 441-448.',
'[10]Athanasiou, K. A., Agrawal, C. M., Barber, F. A., & Burkhart, S. S. (1998). Orthopaedic applications for PLA-PGA biodegradable polymers. Arthroscopy: The Journal of Arthroscopic & Related Surgery, 14(7), 726-737.',
'[11]Lee, J. W., & Gardella, J. A. (2001). In vitro hydrolytic surface degradation of poly (glycolic acid): Role of the surface segregated amorphous region in the induction period of bulk erosion. Macromolecules, 34(12), 3928-3937.',
'[12] Material properties and tissue reaction during degradation of poly (96L/4D-Lactide)- a study in vitro and in rats,JOURNAL OF MATERIAES SCIENCE: MATERIALS IN MEDICINE 6 (1995) 211-217',
'[13] Processing Derived Control of Hydrolytic Degradation and Generation of Shape-Memory in Lactide Copolymers Paakinaho, Kaarlo (2013)',
'[14] Polymer Degradation and Performance-Oxford University Press (2009), (ACS Symposium Series 1004) Mathew C Celina, Norman C Billingham, Jeffrey S Wiggins',
'[15] Azimi B, Nourpanah P, Rabiee M, Arbab S. Poly (∊-caprolactone) Fiber: An Overview. Journal of Engineered Fibers and Fabrics. 2014;9(3).',
'[16] Hartmann, F., Baumgartner, M., & Kaltenbrunner, M. (2020). Becoming Sustainable, The New Frontier in Soft Robotics. Advanced Materials, 2004413.',
'[17] Lam, C. X. F., Savalani, M. M., Teoh, S.-H., & Hutmacher, D. W. (2008). Dynamics ofin vitropolymer degradation of polycaprolactone-based scaffolds: accelerated versus simulated physiological conditions. Biomedical Materials, 3(3), 034108.',
'[18] Bioinspired Nanocomposites for Orthopedic Applications, September 2007',
'[20]Pitt, C. G., Chasalow, F. I., Hibionada, Y. M., Klimas, D. M., & Schindler, A. (1981). Aliphatic polyesters. I. The degradation of poly (ϵ‐caprolactone) in vivo. Journal of applied polymer science, 26(11), 3779-3787.',
'[21]Polym Chem 2010, 1, 296–302',
'[22]Thakur, M., Majid, I., Hussain, S., & Nanda, V. (2021). Poly (ε‐caprolactone): A potential polymer for biodegradable food packaging applications. Packaging Technology and Science, 34(8), 449-461.',
'[23] Green Chem., 2020,22, 4055-4081',
'[24] Biomatter. 2014; 4: e27979.',
'[25]Zada, M. H., Kumar, A., Elmalak, O., Markovitz, E., Icekson, R., & Domb, A. J. (2020). In vitro and in vivo degradation behavior and the long-term performance of biodegradable PLCL balloon implants. International Journal of Pharmaceutics, 574, 118870.',
'[26] Progress in Polymer Science, 2012, 37, 5, 715-765',
'[27] Macromol Chem Phys 2002;203:2630–9',
'[28] Polymer Degradation and Stability 2011, 96, 10, 1882-1889',
'[29] Q. Cai , J. Bei and S. Wang , Polymer, 2002, 43 , 3585 —3591',
'[30] Polymer, 2002, 43 , 3585 —3591',
'[31] J. Biomater. Sci., Polym. Ed., 2013, 24 , 386 —397',
'[32] AIP Advances 2, 042159 (2012)',
'[33] Journal of Biomaterials Science, Polymer Edition, 2013, Issue 4, 24, 386-397',
'[34] Biomater. Sci., Polym. Ed., 2000, 11 , 273 —288',
'[35] Int. J. Polym. Sci., 2016',
'[36] J. Biomater. Sci., Polym. Ed., 2002, 13 , 1163 —1173',
'[37]Wlodarczyk, J., Stojko, M., Musial-Kulik, M., Karpeta-Jarzabek, P., Pastusiak, M., Janeczek, H., ... & Kasperczyk, J. (2022). Dual-jet electrospun PDLGA/PCU nonwovens and their mechanical and hydrolytic degradation properties. Journal of the Mechanical Behavior of Biomedical Materials, 126, 105050.',
'[38]Wlodarczyk, J., Musial-Kulik, M., Jelonek, K., Stojko, M., Karpeta-Jarzabek, P., Pastusiak, M., ... & Kasperczyk, J. (2022). Dual-jet electrospun PDLGA/PCU nonwovens as promising mesh implant materials with controlled release of sirolimus and diclofenac. International Journal of Pharmaceutics, 625, 122113.',
'[39]Vey, E., Roger, C., Meehan, L., Booth, J., Claybourn, M., Miller, A. F., & Saiani, A. (2008). Degradation mechanism of poly (lactic-co-glycolic) acid block copolymer cast films in phosphate buffer solution. Polymer Degradation and Stability, 93(10), 1869-1876.',
'[40]Sabir, M. I., Xu, X., & Li, L. (2009). A review on biodegradable polymeric materials for bone tissue engineering applications. Journal of materials science, 44(21), 5713-5724.',
'[41]Houchin, M. L., & Topp, E. M. (2008). Chemical degradation of peptides and proteins in PLGA: a review of reactions and mechanisms. Journal of pharmaceutical sciences, 97(7), 2395-2404.',
'[42] Materials Science Forum 636-637:825-832',
'[43]Vieira, A. C., Vieira, J. C., Ferra, J. M., Magalhães, F. D., Guedes, R. M., & Marques, A. T. (2011). Mechanical study of PLA–PCL fibers during in vitro degradation. Journal of the mechanical behavior of biomedical materials, 4(3), 451-460.',
'[44]Freier, T., Kunze, C., Nischan, C., Kramer, S., Sternberg, K., Saß, M., ... & Schmitz, K. P. (2002). In vitro and in vivo degradation studies for development of a biodegradable patch based on poly (3-hydroxybutyrate). Biomaterials, 23(13), 2649-2657.',
'[45]Lei, L., Ding, T., Shi, R., Liu, Q., Zhang, L., Chen, D., & Tian, W. (2007). Synthesis, characterization and in vitro degradation of a novel degradable poly ((1, 2-propanediol-sebacate)-citrate) bioelastomer. Polymer degradation and stability, 92(3), 389-396.',
'[46]Ke, Y., Qu, Z., Wu, G., & Wang, Y. (2014). Thermal and in vitro degradation properties of the NH2-containing PHBV films. Polymer degradation and stability, 105, 59-67.',
'[47]Carli, L. N., Crespo, J. S., & Mauler, R. S. (2011). PHBV nanocomposites based on organomodified montmorillonite and halloysite: The effect of clay type on the morphology and thermal and mechanical properties. Composites Part A: Applied Science and Manufacturing, 42(11), 1601-1608.',
'[48] Frontiers in Bioengineering and Biotechnology, 2020, 8, 2296-4185',
'[49] BIOMATERIALS FOR MEMS, Chiao, M. Pan Stanford Pub., 2011.',
'[50]Ke, Y., Qu, Z., Wu, G., & Wang, Y. (2014). Thermal and in vitro degradation properties of the NH2-containing PHBV films. Polymer degradation and stability, 105, 59-67.',
'[51]Utsunomia, C., Ren, Q., & Zinn, M. (2020). Poly (4-hydroxybutyrate): Current state and perspectives. Frontiers in Bioengineering and Biotechnology, 8, 257.',
'[52]Keridou, I., Franco, L., Martínez, J. C., Turon, P., Del Valle, L. J., & Puiggalí, J. (2022). Electrospun scaffolds for wound healing applications from poly (4‐hydroxybutyrate): A biobased and biodegradable linear polymer with high elastomeric properties. Journal of Applied Polymer Science, 139(1), 51447.',
'[53]Torricelli, F., Alessandri, I., Macchia, E., Vassalini, I., Maddaloni, M., & Torsi, L. (2022). Green Materials and Technologies for Sustainable Organic Transistors. Advanced Materials Technologies, 7(2), 2100445.',
'[54] Declan M. Devine - Bioresorbable Polymers and their Biomedical Applications-Smithers Rapra Technology (2017)',
'[55] F. J. Buchanan - Degradation Rate of Bioresorbable Materials_ Prediction and Evaluation -CRC Press (2008)',
'[57] Martins, J. A., Lach, A. A., Morris, H. L., Carr, A. J., & Mouthuy, P.-A. (2019). Polydioxanone implants: A systematic review on safety and performance in patients. Journal of Biomaterials Applications, 088532821988884.',
'[58] AN ELECTROSPUN POLYDIOXANONE PATCH FOR THE LOCALISATION OF BIOLOGICAL THERAPIES DURING TENDON REPAIR,European Cells and Materials Vol. 24 2012 (pages 344-357)',
'[59] Considerations for the design of polymeric biodegradable products. Journal of Polymer Engineering, 33(4).(2013)',
'[60] Tuning the mechanical properties and degradation properties of polydioxanone isothermal annealing, October 2020Turkish Journal of Chemistry 44(5):1430-1444',
'[61]Pan, W., Bai, Z., Su, T., & Wang, Z. (2018). Enzymatic degradation of poly (butylene succinate) with different molecular weights by cutinase. International journal of biological macromolecules, 111, 1040-1046.',
'[62]Mochane, M. J., Magagula, S. I., Sefadi, J. S., & Mokhena, T. C. (2021). A review on green composites based on natural fiber-reinforced polybutylene succinate (PBS). Polymers, 13(8), 1200.',
'[63]Wang, Y. W., Mo, W., Yao, H., Wu, Q., Chen, J., & Chen, G. Q. (2004). Biodegradation studies of poly (3-hydroxybutyrate-co-3-hydroxyhexanoate). Polymer degradation and stability, 85(2), 815-821.',
'[64] Polymer Degradation and Stability, 2015, 122, 77-87',
'[65]Fukushima, K. (2016). Poly (trimethylene carbonate)-based polymers engineered for biodegradable functional biomaterials. Biomaterials science, 4(1), 9-24.',
'[66] Appl Environ Microbiol. 1999 Sep; 65(9): 4220–4222.',
'[67]Fukushima, K., Rasyida, A., & Yang, M. C. (2013). Characterization, degradation and biocompatibility of PBAT based nanocomposites. Applied Clay Science, 80, 291-298.',
'[68]Muthuraj, R., Misra, M., & Mohanty, A. K. (2015). Hydrolytic degradation of biodegradable polyesters under simulated environmental conditions. Journal of Applied Polymer Science, 132(27).',
'[69]Ding, T., Liu, Q., Shi, R., Tian, M., Yang, J., & Zhang, L. (2006). Synthesis, characterization and in vitro degradation study of a novel and rapidly degradable elastomer. Polymer Degradation and Stability, 91(4), 733-739.',
'[70]Unger, F., Westedt, U., Hanefeld, P., Wombacher, R., Zimmermann, S., Greiner, A., ... & Kissel, T. (2007). Poly (ethylene carbonate): A thermoelastic and biodegradable biomaterial for drug eluting stent coatings?. Journal of controlled release, 117(3), 312-321.',
'[71]Dadsetan, M., Christenson, E. M., Unger, F., Ausborn, M., Kissel, T., Hiltner, A., & Anderson, J. M. (2003). In vivo biocompatibility and biodegradation of poly (ethylene carbonate). Journal of controlled release, 93(3), 259-270.',
'[72]Turner, B., Ramesh, S., Menegatti, S., & Daniele, M. (2022). Resorbable elastomers for implantable medical devices: highlights and applications. Polymer International, 71(5), 552-561.',
'[73]Yang, J., Webb, A. R., & Ameer, G. A. (2004). Novel citric acid‐based biodegradable elastomers for tissue engineering. Advanced Materials, 16(6), 511-516.',
'[74]Gyawali, D., Tran, R. T., Guleserian, K. J., Tang, L., & Yang, J. (2010). Citric-acid-derived photo-cross-linked biodegradable elastomers. Journal of Biomaterials Science, Polymer Edition, 21(13), 1761-1782.',
'[75] Polymers 2019, 11(9), 1516',
'[76] Macromol. Biosci.2007,7,1217–1224',
'[77]  Macromol Mater Eng. 2011 Dec 12; 296(12): 1149–1157.',
'[78] Biomaterials. 2008 Dec; 29(35): 4637–4649.',
'[79]Pomerantseva, I., Krebs, N., Hart, A., Neville, C. M., Huang, A. Y., & Sundback, C. A. (2009). Degradation behavior of poly (glycerol sebacate). Journal of Biomedical Materials Research Part A: An Official Journal of The Society for Biomaterials, The Japanese Society for Biomaterials, and The Australian Society for Biomaterials and the Korean Society for Biomaterials, 91(4), 1038-1047.',
'[80]Salehi, S., Bahners, T., Gutmann, J. S., Gao, S. L., Mäder, E., & Fuchsluger, T. A. (2014). Characterization of structural, mechanical and nano-mechanical properties of electrospun PGS/PCL fibers. Rsc Advances, 4(33), 16951-16957.',
'[81] Macromol Biosci, 6 (2006), pp. 333-339',
'[82]Lei, L., Ding, T., Shi, R., Liu, Q., Zhang, L., Chen, D., & Tian, W. (2007). Synthesis, characterization and in vitro degradation of a novel degradable poly((1,2-propanediol-sebacate)-citrate) bioelastomer. Polymer Degradation and Stability, 92(3), 389–396.',
'[83] Polymer 2009;50:1682–91.',
'[84] Quanyong Liu et al 2009 Biomed. Mater. 4 025015',
'[85] J Biomater Sci Polym Ed 2009;20:1567–78',
'[86] J.P. Bruggeman et al. / Biomaterials 29 (2008) 4726–4735',
'[87] Ramaraju H, Solorio LD, Bocks ML, Hollister SJ (2020) Degradation properties of a biodegradable shape memory elastomer, poly(glycerol dodecanoate), for soft tissue repair. PLoS ONE 15(2): e0229112',
'[88] Biomaterials 30 (2009) 6479–6484',
'[89] Macromolecules 2008, 41, 17, 6347–6352',
'[91] Eur Polym J 2009;45:3247–54',
'[92] Effect of environmental conditions on the durability of polycarbonate for the protection of cultural heritage sites, Sage journals, December 17, 2019',
'[93] Sommerfeld, S. D., Zhang, Z., Costache, M. C., Vega, S. L., & Kohn, J. (2014). Enzymatic Surface Erosion of High Tensile Strength Polycarbonates Based on Natural Phenols. Biomacromolecules, 15(3), 830–836.',
'[94]Wang, Z., Yu, L., Ding, M., Tan, H., Li, J., & Fu, Q. (2011). Preparation and rapid degradation of nontoxic biodegradable polyurethanes based on poly (lactic acid)-poly (ethylene glycol)-poly (lactic acid) and l-lysine diisocyanate. Polymer Chemistry, 2(3), 601-607.',
'[95]Pfohl, P., Bahl, D., Rückel, M., Wagner, M., Meyer, L., Bolduan, P., ... & Wohlleben, W. (2022). Effect of Polymer Properties on the Biodegradation of Polyurethane Microplastics. Environmental Science & Technology.',
'[96] D. Liaw, J. Appl. Polym. Sci. 1997, 66, 1251.',
'[97] Appl Polym Sci, 114 (2009), pp. 1464-1470',
'[98] Kenawy, E.-R., Kamoun, E. A., Mohy Eldin, M. S., & El-Meligy, M. A. (2014). Physically crosslinked poly(vinyl alcohol)-hydroxyethyl starch blend hydrogel membranes: Synthesis and characterization for biomedical applications. Arabian Journal of Chemistry, 7(3), 372–380.',
'[101] Potential soluble substrates for transient electronics applications: A review, AIP Advances 12, 050701 (2022)',
'[102]Reed, A. M., & Gilding, D. K. (1981). Biodegradable polymers for use in surgery—poly (ethylene oxide)/poly (ethylene terephthalate)(PEO/PET) copolymers: 2. In vitro degradation. Polymer, 22(4), 499-504.',
'[103]Na, Y. H., He, Y., Nishiwaki, T., Inagawa, Y., Osanai, Y., Matsumura, S., ... & Inoue, Y. (2003). Phase-separation enhanced enzymatic degradation of atactic poly (R, S-3-hydroxybutyrate) in the blends with poly (methyl methacrylate). Polymer degradation and stability, 79(3), 535-545.',
'[104]Fay, F., Linossier, I., Peron, J. J., Langlois, V., & Vallee-Rehel, K. (2007). Antifouling activity of marine paints: Study of erosion. Progress in organic coatings, 60(3), 194-206.',
'[105] Biomaterials 2004;25:5261–9',
'[106] Polym. Degrad. Stab., 2013, 98 , 133 —143',
'[107] Polym. Adv. Technol., 2005, 16 , 608 —615',
'[108] J Appl Polym Sci.2022;139:e52968',
'[109] Polym. Adv. Technol., 2012, 23 , 565 —573',
'[110] Polym. Adv. Technol., 2018, 29 , 1684 —1696',
'[111] Synthesis, degradation and biocompatibility of tyrosine-derived polycarbonate scaffolds. Journal of Materials Chemistry, 20(40), 8885.(2010)',
'[112] Xia, H., Suo, Z. Y., Qiang, G. J., & Chang, C. J. (2008). Synthesis, characterization, and degradation of a novel L-tyrosine-derived polycarbonate for potential biomaterial applications. Journal of Applied Polymer Science, 110(4), 2168–2178.',
'[113] Murthy, N. S., Wang, W., & Kohn, J. (2010). Microphase separation in copolymers of hydrophilic PEG blocks and hydrophobic tyrosine-derived segments using simultaneous SAXS/WAXS/DSC. Polymer, 51(17), 3978–3988.',
'[114] Cui, Z., Peng, Y., Li, K., Peng, J., Zhao, H., Turng, L.-S., & Shen, C. (2013). The degradation rate of polyanhydride (poly(sebacic acid), diacetoxy terminated, PSADT). Journal of Wuhan University of Technology-Mater. Sci. Ed., 28(4), 793–797.',
'[115] Biodegradable Polyanhydrides as Encapsulation Layers for Transient Electronics. Advanced Functional Materials, 30(31), 2000941. (2020)',
'[116] Yeoh, F. H., Lee, C. S., Kang, Y. B., Wong, S. F., Cheng, S. F., & Ng, W. S. (2020). Production of Biodegradable Palm Oil-Based Polyurethane as Potential Biomaterial for Biomedical Applications. Polymers, 12(8), 1842.',
'[117] Snyder SS, Anastasiou TJ, Uhrich KE. In Vitro Degradation of an Aromatic Polyanhydride with Enhanced Thermal Properties. Polym Degrad Stab. 2015 May 1;115:70-76. ',
'[118] Design and fabrication of salicylic acid-based polyanhydride devices for wound healing and tissue regeneration, New Brunswick and University of Medicine and Dentistry of New Jersey ProQuest Dissertations Publishing,  2013. 3597771.',
'[119]Zhang, Q., Yan, Y., Li, S., & Feng, T. (2010). The synthesis and characterization of a novel biodegradable and electroactive polyphosphazene for nerve regeneration. Materials Science and Engineering: C, 30(1), 160-166.',
'[120]Ogueri, K. S., Ivirico, J. L. E., Nair, L. S., Allcock, H. R., & Laurencin, C. T. (2017). Biodegradable polyphosphazene-based blends for regenerative engineering. Regenerative engineering and translational medicine, 3(1), 15-31.',
'[121]Nichol, J. L., & Allcock, H. R. (2015). Polyphosphazenes with amino acid citronellol ester side groups for biomedical applications. European Polymer Journal, 62, 214-221.',
'[122]Zhou, J. F., Wang, Y. G., Cheng, L., Wu, Z., Sun, X. D., & Peng, J. (2016). Preparation of polypyrrole-embedded electrospun poly (lactic acid) nanofibrous scaffolds for nerve tissue engineering. Neural regeneration research, 11(10), 1644.',
'[123]Zhou, J., Cheng, L., Sun, X., Wang, X., Jin, S., Li, J., & Wu, Q. (2016). Neurogenic differentiation of human umbilical cord mesenchymal stem cells on aligned electrospun polypyrrole/polylactide composite nanofibers with electrical stimulation. Frontiers of Materials Science, 10(3), 260-269.',
'[124]van Dijk-Wolthuis, W. N. E., Hoogeboom, J. A. M., Van Steenbergen, M. J., Tsang, S. K. Y., & Hennink, W. E. (1997). Degradation and release behavior of dextran-based hydrogels. Macromolecules, 30(16), 4639-4645.',
'[125]Andrabi, S. M., Majumder, S., Gupta, K. C., & Kumar, A. (2020). Dextran based amphiphilic nano-hybrid hydrogel system incorporated with curcumin and cerium oxide nanoparticles for wound healing. Colloids and Surfaces B: Biointerfaces, 195, 111263.',
'[126] Shi, L., Zhang, Y., & Ossipov, D. (2017). Enzymatic degradation of hyaluronan hydrogels with different capacity for in situ bio-mineralization. Biopolymers, 109(2), e23090.',
'[127] BETTELHEIM, F. A. (1958). Crystalline Sodium Hyaluronate. Nature, 182(4645), 1301–1302.',
'[128] Larrañeta, E., Henry, M., Irwin, N. J., Trotter, J., Perminova, A. A., & Donnelly, R. F. (2018). Synthesis and characterization of hyaluronic acid hydrogels crosslinked using a solvent-free process for potential biomedical applications. Carbohydrate Polymers, 181, 1194–1205.',
'[129] Tavsanli, B., & Okay, O. (2017). Mechanically strong hyaluronic acid hydrogels with an interpenetrating network structure. European Polymer Journal, 94, 185–195.',
'[130]Teramoto, N., & Shibata, M. (2006). Synthesis and properties of pullulan acetate. Thermal properties, biodegradability, and a semi-clear gel formation in organic solvents. Carbohydrate polymers, 63(4), 476-481.',
'[131] The enzymatic degradation and swelling properties of chitosan matrices with different degrees of N-acetylation. Carbohydrate Research, 340(15), 2403–2410. (2005)',
'[132] Dang, Q. F., Yan, J. Q., Li, J. J., Cheng, X. J., Liu, C. S., & Chen, X. G. (2011). Controlled gelation temperature, pore diameter and degradation of a highly porous chitosan-based hydrogel. Carbohydrate Polymers, 83(1), 171–178.',
'[133] Elastic Modulus of the Crystalline Regions of Chitin and Chitosan,Journal of Polymer Science Part B: Polymer Physics, 37(11), 1191–1196.',
'[134] Nanoscale Res Lett. 2019; 14: 56.',
'[135]Navarro, M. E. L. B. A., Ginebra, M. P., Planell, J. A., Barrias, C. C., & Barbosa, M. A. (2005). In vitro degradation behavior of a novel bioresorbable composite material based on PLA and a soluble CaP glass. Acta Biomaterialia, 1(4), 411-419.',
'[136]Alabbasi, A., Liyanaarachchi, S., & Kannan, M. B. (2012). Polylactic acid coating on a biodegradable magnesium alloy: An in vitro degradation study by electrochemical impedance spectroscopy. Thin Solid Films, 520(23), 6841-6844.',
'[137]Tokiwa, Y., & Calabia, B. P. (2006). Biodegradability and biodegradation of poly (lactide). Applied microbiology and biotechnology, 72(2), 244-251.',
'[139]Salomez, M., George, M., Fabre, P., Touchaleaume, F., Cesar, G., Lajarrige, A., & Gastaldi, E. (2019). A comparative study of degradation mechanisms of PHBV and PBSA under laboratory-scale composting conditions. Polymer degradation and stability, 167, 102-113.',
'[140]Gigli, M., Negroni, A., Zanaroli, G., Lotti, N., Fava, F., & Munari, A. (2013). Environmentally friendly PBS-based copolyesters containing PEG-like subunit: Effect of block length on solid-state properties and enzymatic degradation. Reactive and Functional Polymers, 73(5), 764-771.',
'[141]Held, M., Pichler, A., Chabeda, J., Lam, N., Hindenberg, P., Romero‐Nieto, C., & Hernandez‐Sosa, G. (2022). Soft electronic platforms combining elastomeric stretchability and biodegradability. Advanced Sustainable Systems, 6(2), 2100035.',
'[142] In vitro degradation and bioactivity of poly(propylene fumarate)/bioactive glass sintered microsphere scaffolds for bone tissue engineering. Science and Engineering of Composite Materials, 0(0) (2014).',
'[143] Diez-Pascual, A. (2017). Tissue Engineering Bionanocomposites Based on Poly(propylene fumarate). Polymers, 9(12), 260.',
'[144] Kasper, F. K., Tanahashi, K., Fisher, J. P., & Mikos, A. G. (2009). Synthesis of poly(propylene fumarate). Nature Protocols, 4(4), 518–525.',
'[145] Biodegradable Synthetic Polymers For Tissue Engineering., June 2003 European Cells & Materials 5(1):1-16; discussion 16',
'[146] Mechanical properties of poly(propylene fumarate)/nanotube composites: experimental results and theoretical predictions,IOP Conference Series: Materials Science and Engineering, Volume 383',
'[147] Lee, K.-W., Wang, S., Lu, L., Jabbari, E., Currier, B. L., & Yaszemski, M. J. (2006). Fabrication and Characterization of Poly(Propylene Fumarate) Scaffolds with Controlled Pore Structures Using 3-Dimensional Printing and Injection Molding. Tissue Engineering, 12(10), 2801–2811.',
'[148] Phan, V. H. G. et al. Poly(amino carbonate urethane)-based biodegradable, temperature and pH-sensitive injectable hydrogels for sustained human growth hormone delivery. Sci. Rep. 6, 29978',
'[149]Lei, T., Guan, M., Liu, J., Lin, H. C., Pfattner, R., Shaw, L., ... & Bao, Z. (2017). Biocompatible and totally disintegrable semiconducting polymer for ultrathin and ultralightweight transient electronics. Proceedings of the National Academy of Sciences, 114(20), 5107-5112.',
'[150] Pei, D., Wang, Z., Peng, Z., Zhang, J., Deng, Y., Han, Y., ... & Geng, Y. (2020). Impact of molecular weight on the mechanical and electrical properties of a high-mobility diketopyrrolopyrrole-based conjugated polymer. Macromolecules, 53(11), 4490-4500.',
'[151]Khanra, S., Cipriano T., Lam, T., White, T. A., Fileti, E. E., Alves, W. A., & Guha, S. (2015). Self‐Assembled Peptide–Polyfluorene Nanocomposites for Biodegradable Organic Electronics. Advanced Materials Interfaces, 2(14), 1500265.',
'[152]Ghoshal, S., Khan, M. A., Khan, R. A., & Sarwaruddin Chowdhury, A. M. (2010). Study on the thermo-mechanical and biodegradable properties of shellac films grafted with acrylic monomers by gamma radiation. Journal of Polymers and the Environment, 18(3), 216-223.',
'[153]Feig, V. R., Tran, H., & Bao, Z. (2018). Biodegradable polymeric materials in degradable electronic devices. ACS central science, 4(3), 337-348.',
'[154]Ghoshal, S., Khan, M. A., Gul-E-Noor, F., & Khan, R. A. (2009). Gamma radiation induced biodegradable shellac films treated by acrylic monomer and ethylene glycol. Journal of Macromolecular Science®, Part A: Pure and Applied Chemistry, 46(10), 975-982.',
'[155]Vignali A, Iannace S, Falcone G, Utzeri R, Stagnaro P, Bertini F. Lightweight Poly(ε-Caprolactone) Composites with Surface Modified Hollow Glass Microspheres for Use in Rotational Molding: Thermal, Rheological and Mechanical Properties. Polymers (Basel). 2019 Apr 4;11(4):624.',
]